//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdbool.h>
#include <stdint.h>

// ------------------- Function Prototypes --------------------

void _Z14localMemKernelPii(int32_t * a1, int32_t a2);
void _Z15globalMemKernelPKiPii(int32_t * a1, int32_t * a2, int32_t a3);
void _Z15sharedMemKernelPKiPii(int32_t * a1, int32_t * a2, int32_t a3);
int32_t custom_lop3(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t custom_plop3(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t custom_ulop3(int32_t a1, int32_t a2, int32_t a3, int32_t a4);

// --------------------- Global Variables ---------------------

int32_t g1[4096];

// ------------------------ Functions -------------------------

int32_t custom_lop3(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    switch (a1) {
        case 128: {
            break;
        }
        case 0: {
            break;
        }
        case 64: {
            break;
        }
        case 254: {
            break;
        }
        case 255: {
            break;
        }
        case 26: {
            break;
        }
        case 51: {
            break;
        }
        case 192: {
            break;
        }
        case 8: {
            break;
        }
        case 60: {
            break;
        }
        case 15: {
            break;
        }
        case 85: {
            break;
        }
        case 252: {
            break;
        }
        case 248: {
            break;
        }
    }
    return -1;
}

int32_t custom_plop3(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    switch (a1) {
        case 128: {
            break;
        }
        case 0: {
            break;
        }
        case 64: {
            break;
        }
        case 254: {
            break;
        }
        case 255: {
            break;
        }
        case 26: {
            break;
        }
        case 51: {
            break;
        }
        case 192: {
            break;
        }
        case 8: {
            break;
        }
        case 60: {
            break;
        }
        case 15: {
            break;
        }
        case 85: {
            break;
        }
        case 252: {
            break;
        }
        case 248: {
            break;
        }
    }
    return -1;
}

int32_t custom_ulop3(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    switch (a1) {
        case 128: {
            break;
        }
        case 0: {
            break;
        }
        case 64: {
            break;
        }
        case 254: {
            break;
        }
        case 255: {
            break;
        }
        case 26: {
            break;
        }
        case 51: {
            break;
        }
        case 192: {
            break;
        }
        case 8: {
            break;
        }
        case 60: {
            break;
        }
        case 15: {
            break;
        }
        case 85: {
            break;
        }
        case 252: {
            break;
        }
        case 248: {
            break;
        }
    }
    return -1;
}

void _Z14localMemKernelPii(int32_t * a1, int32_t a2) {
    int32_t v1 = llvm_nvvm_read_ptx_sreg_ctaid_x() * llvm_nvvm_read_ptx_sreg_ntid_x() + llvm_nvvm_read_ptx_sreg_tid_x();
    if (v1 < a2 || false) {
        int64_t v2 = (int64_t)v1 * (int64_t)4 + (int64_t)a1;
        *(int32_t *)(char *)(0x100000000 * (int64_t)(int32_t)((v2 & -0x100000000) >> 32) | (int64_t)(int32_t)v2) = 1 + v1;
    }
}

void _Z15sharedMemKernelPKiPii(int32_t * a1, int32_t * a2, int32_t a3) {
    int32_t v1 = llvm_nvvm_read_ptx_sreg_ctaid_x();
    int32_t v2 = llvm_nvvm_read_ptx_sreg_tid_x();
    uint32_t v3 = v1 * llvm_nvvm_read_ptx_sreg_ntid_x() + v2;
    bool v4 = v3 >= a3 & true;
    if (!v4) {
        int64_t v5 = (int64_t)v3 * (int64_t)4 + (int64_t)a1;
        int32_t v6 = *(int32_t *)(char *)(0x100000000 * (int64_t)(int32_t)((v5 & -0x100000000) >> 32) | (int64_t)(int32_t)v5);
        *(int32_t *)&((char *)&g1)[(int64_t)(4 * v2)] = 1 + v6;
    }
    llvm_nvvm_barrier0();
    if (!v4) {
        int32_t v7 = *(int32_t *)&((char *)&g1)[(int64_t)(4 * v2)];
        int64_t v8 = (int64_t)v3 * (int64_t)4 + (int64_t)a2;
        *(int32_t *)(char *)(0x100000000 * (int64_t)(int32_t)((v8 & -0x100000000) >> 32) | (int64_t)(int32_t)v8) = v7;
    }
}

void _Z15globalMemKernelPKiPii(int32_t * a1, int32_t * a2, int32_t a3) {
    uint32_t v1 = llvm_nvvm_read_ptx_sreg_ctaid_x() * llvm_nvvm_read_ptx_sreg_ntid_x() + llvm_nvvm_read_ptx_sreg_tid_x();
    if (v1 < a3 || false) {
        int64_t v2 = (int64_t)v1 * (int64_t)4 + (int64_t)a1;
        int32_t v3 = *(int32_t *)(char *)(0x100000000 * (int64_t)(int32_t)((v2 & -0x100000000) >> 32) | (int64_t)(int32_t)v2);
        int64_t v4 = (int64_t)v1 * (int64_t)4 + (int64_t)a2;
        *(int32_t *)(char *)(0x100000000 * (int64_t)(int32_t)((v4 & -0x100000000) >> 32) | (int64_t)(int32_t)v4) = 1 + v3;
    }
}

// --------------------- Meta-Information ---------------------

// Detected functions: 6

