//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdbool.h>
#include <stdint.h>

// ----------------- Float Types Definitions ------------------

typedef float float32_t;

// ------------------------ Structures ------------------------

struct struct1 {
    int32_t e0;
    bool e1;
};

// ------------------- Function Prototypes --------------------

void _Z15ffn_relu_kernelPKfS0_S0_Pfiii(float32_t * a1, float32_t * a2, float32_t * a3, float32_t * a4, int32_t a5, int32_t a6, int32_t a7);
void _Z18linear_proj_kernelPKfS0_S0_Pfiii(float32_t * a1, float32_t * a2, float32_t * a3, float32_t * a4, int32_t a5, int32_t a6, int32_t a7);
int32_t custom_lop3(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t custom_plop3(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t custom_ulop3(int32_t a1, int32_t a2, int32_t a3, int32_t a4);

// ------------------------ Functions -------------------------

int32_t custom_lop3(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    switch (a1) {
        case 128: {
            break;
        }
        case 0: {
            break;
        }
        case 64: {
            break;
        }
        case 254: {
            break;
        }
        case 255: {
            break;
        }
        case 26: {
            break;
        }
        case 51: {
            break;
        }
        case 192: {
            break;
        }
        case 8: {
            break;
        }
        case 60: {
            break;
        }
        case 15: {
            break;
        }
        case 85: {
            break;
        }
        case 252: {
            break;
        }
        case 248: {
            break;
        }
    }
    return -1;
}

int32_t custom_plop3(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    switch (a1) {
        case 128: {
            break;
        }
        case 0: {
            break;
        }
        case 64: {
            break;
        }
        case 254: {
            break;
        }
        case 255: {
            break;
        }
        case 26: {
            break;
        }
        case 51: {
            break;
        }
        case 192: {
            break;
        }
        case 8: {
            break;
        }
        case 60: {
            break;
        }
        case 15: {
            break;
        }
        case 85: {
            break;
        }
        case 252: {
            break;
        }
        case 248: {
            break;
        }
    }
    return -1;
}

int32_t custom_ulop3(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    switch (a1) {
        case 128: {
            break;
        }
        case 0: {
            break;
        }
        case 64: {
            break;
        }
        case 254: {
            break;
        }
        case 255: {
            break;
        }
        case 26: {
            break;
        }
        case 51: {
            break;
        }
        case 192: {
            break;
        }
        case 8: {
            break;
        }
        case 60: {
            break;
        }
        case 15: {
            break;
        }
        case 85: {
            break;
        }
        case 252: {
            break;
        }
        case 248: {
            break;
        }
    }
    return -1;
}

void _Z15ffn_relu_kernelPKfS0_S0_Pfiii(float32_t * a1, float32_t * a2, float32_t * a3, float32_t * a4, int32_t a5, int32_t a6, int32_t a7) {
    struct struct1 v1;
    struct struct1 v2;
    struct struct1 v3;
    struct struct1 v4;
    struct struct1 v5;
    struct struct1 v6;
    struct struct1 v7;
    struct struct1 v8;
    struct struct1 v9;
    struct struct1 v10;
    struct struct1 v11;
    struct struct1 v12;
    struct struct1 v13;
    struct struct1 v14;
    struct struct1 v15;
    struct struct1 v16;
    int32_t v17 = llvm_nvvm_read_ptx_sreg_ctaid_x();
    int32_t v18 = llvm_nvvm_read_ptx_sreg_tid_x();
    int32_t v19 = llvm_nvvm_read_ptx_sreg_ctaid_y();
    int32_t v20 = llvm_nvvm_read_ptx_sreg_tid_y();
    int32_t v21 = v17 * llvm_nvvm_read_ptx_sreg_ntid_x() + v18;
    v19 = v19 * llvm_nvvm_read_ptx_sreg_ntid_y() + v20;
    if (v19 >= a5 || v21 >= a7 && true) {
        return;
    }
    int64_t v22 = (int64_t)v21 * (int64_t)4 + (int64_t)a3;
    int32_t v23 = v22;
    float32_t v24 = *(float32_t *)(char *)(0x100000000 * (int64_t)(int32_t)((v22 & -0x100000000) >> 32) | (int64_t)v23);
    *(float32_t *)&v23 = v24;
    int32_t v25;
    uint32_t v26;
    int32_t v27;
    int32_t v28;
    int32_t v29;
    int32_t v30;
    int32_t v31;
    int32_t v32;
    int32_t v33;
    int32_t v34;
    int32_t v35;
    int32_t v36;
    int32_t v37;
    int32_t v38;
    int32_t v39;
    if (a6 < 1 || false) {
        goto lab__L_x_0;
    } else {
        v25 = a6 & 3;
        v37 = 0;
        if (a6 < 4 || false) {
            goto lab__L_x_1;
        } else {
            int32_t v40 = a6 - v25;
            int64_t v41 = (int64_t)a2;
            int32_t v42 = (v41 & -0x100000000) >> 32;
            int32_t v43 = v41;
            v26 = v21 * a6;
            bool v44 = v40 > 0 & true;
            v37 = 0;
            int64_t v45 = (int64_t)(v19 * a6) * (int64_t)4 + (int64_t)a1;
            int32_t v46 = v45;
            v18 = (v45 & -0x100000000) >> 32;
            if (!v44) {
                v38 = v43;
                v27 = v40;
                v39 = v42;
                v36 = v46;
                goto lab__L_x_2_preheader;
            } else {
                int32_t v47;
                int32_t v48;
                int32_t v49;
                int32_t v50;
                int32_t v51;
                int32_t v52;
                int32_t v53;
                int32_t v54;
                int32_t v55;
                uint32_t v56;
                int32_t v57;
                int32_t v58;
                if (v40 > 12 && true) {
                    float32_t v59 = *(float32_t *)(char *)(0x100000000 * (int64_t)v18 | (int64_t)v46);
                    *(float32_t *)&v29 = v59;
                    float32_t v60 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v46) + 4);
                    *(float32_t *)&v30 = v60;
                    int64_t v61 = (int64_t)v26 * (int64_t)4 + (int64_t)v43;
                    uint32_t v62 = (int32_t)((v61 & -0x100000000) >> 32);
                    uint32_t v63 = (int32_t)v61;
                    float32_t v64 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v46) + 8);
                    *(float32_t *)&v32 = v64;
                    float32_t v65 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v46) + 12);
                    *(float32_t *)&v34 = v65;
                    float32_t v66 = *(float32_t *)(char *)(0x100000000 * (int64_t)v62 | (int64_t)v63);
                    *(float32_t *)&v28 = v66;
                    float32_t v67 = *(float32_t *)(char *)((0x100000000 * (int64_t)v62 | (int64_t)v63) + 4);
                    *(float32_t *)&v31 = v67;
                    float32_t v68 = *(float32_t *)(char *)((0x100000000 * (int64_t)v62 | (int64_t)v63) + 8);
                    *(float32_t *)&v33 = v68;
                    float32_t v69 = *(float32_t *)(char *)((0x100000000 * (int64_t)v62 | (int64_t)v63) + 12);
                    *(float32_t *)&v35 = v69;
                    float32_t v70 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v46) + 16);
                    *(float32_t *)&v48 = v70;
                    float32_t v71 = *(float32_t *)(char *)((0x100000000 * (int64_t)v62 | (int64_t)v63) + 16);
                    *(float32_t *)&v49 = v71;
                    float32_t v72 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v46) + 20);
                    *(float32_t *)&v50 = v72;
                    float32_t v73 = *(float32_t *)(char *)((0x100000000 * (int64_t)v62 | (int64_t)v63) + 20);
                    *(float32_t *)&v51 = v73;
                    float32_t v74 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v46) + 24);
                    *(float32_t *)&v52 = v74;
                    float32_t v75 = *(float32_t *)(char *)((0x100000000 * (int64_t)v62 | (int64_t)v63) + 24);
                    *(float32_t *)&v53 = v75;
                    float32_t v76 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v46) + 28);
                    *(float32_t *)&v54 = v76;
                    float32_t v77 = *(float32_t *)(char *)((0x100000000 * (int64_t)v62 | (int64_t)v63) + 28);
                    *(float32_t *)&v55 = v77;
                    float32_t v78 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v46) + 32);
                    int32_t v79;
                    *(float32_t *)&v79 = v78;
                    float32_t v80 = *(float32_t *)(char *)((0x100000000 * (int64_t)v62 | (int64_t)v63) + 32);
                    int32_t v81;
                    *(float32_t *)&v81 = v80;
                    float32_t v82 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v46) + 36);
                    int32_t v83;
                    *(float32_t *)&v83 = v82;
                    float32_t v84 = *(float32_t *)(char *)((0x100000000 * (int64_t)v62 | (int64_t)v63) + 36);
                    int32_t v85;
                    *(float32_t *)&v85 = v84;
                    float32_t v86 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v46) + 40);
                    int32_t v87;
                    *(float32_t *)&v87 = v86;
                    float32_t v88 = *(float32_t *)(char *)((0x100000000 * (int64_t)v62 | (int64_t)v63) + 40);
                    int32_t v89;
                    *(float32_t *)&v89 = v88;
                    float32_t v90 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v46) + 44);
                    int32_t v91;
                    *(float32_t *)&v91 = v90;
                    float32_t v92 = *(float32_t *)(char *)((0x100000000 * (int64_t)v62 | (int64_t)v63) + 44);
                    int32_t v93;
                    *(float32_t *)&v93 = v92;
                    float32_t v94 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v46) + 48);
                    int32_t v95;
                    *(float32_t *)&v95 = v94;
                    float32_t v96 = *(float32_t *)(char *)((0x100000000 * (int64_t)v62 | (int64_t)v63) + 48);
                    int32_t v97;
                    *(float32_t *)&v97 = v96;
                    float32_t v98 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v46) + 52);
                    int32_t v99;
                    *(float32_t *)&v99 = v98;
                    float32_t v100 = *(float32_t *)(char *)((0x100000000 * (int64_t)v62 | (int64_t)v63) + 52);
                    int32_t v101;
                    *(float32_t *)&v101 = v100;
                    float32_t v102 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v46) + 56);
                    int32_t v103;
                    *(float32_t *)&v103 = v102;
                    float32_t v104 = *(float32_t *)(char *)((0x100000000 * (int64_t)v62 | (int64_t)v63) + 56);
                    int32_t v105;
                    *(float32_t *)&v105 = v104;
                    float32_t v106 = *(float32_t *)(char *)((0x100000000 * (int64_t)v62 | (int64_t)v63) + 60);
                    int32_t v107;
                    *(float32_t *)&v107 = v106;
                    float32_t v108 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v46) + 60);
                    int32_t v109;
                    *(float32_t *)&v109 = v108;
                    int32_t v110 = v40 - 16;
                    v1 = llvm_uadd_with_overflow_i32(v43, 64);
                    v2 = llvm_uadd_with_overflow_i32(v1.e0, 0);
                    int32_t v111 = v2.e0;
                    v3 = llvm_uadd_with_overflow_i32(v46, 64);
                    v4 = llvm_uadd_with_overflow_i32(v3.e0, 0);
                    int32_t v112 = v4.e0;
                    int32_t v113 = v42 + (int32_t)(v1.e1 | v2.e1) + (int32_t)0;
                    v37 += 16;
                    v18 = v18 + (int32_t)(v3.e1 | v4.e1) + (int32_t)0;
                    float32_t v114 = *(float32_t *)&v23;
                    *(float32_t *)&v28 = *(float32_t *)&v28 * *(float32_t *)&v29 + v114;
                    float32_t v115 = *(float32_t *)&v28;
                    *(float32_t *)&v28 = *(float32_t *)&v31 * *(float32_t *)&v30 + v115;
                    float32_t v116 = *(float32_t *)&v28;
                    *(float32_t *)&v28 = *(float32_t *)&v33 * *(float32_t *)&v32 + v116;
                    float32_t v117 = *(float32_t *)&v28;
                    *(float32_t *)&v28 = *(float32_t *)&v35 * *(float32_t *)&v34 + v117;
                    float32_t v118 = *(float32_t *)&v28;
                    *(float32_t *)&v28 = *(float32_t *)&v49 * *(float32_t *)&v48 + v118;
                    float32_t v119 = *(float32_t *)&v28;
                    *(float32_t *)&v28 = *(float32_t *)&v51 * *(float32_t *)&v50 + v119;
                    float32_t v120 = *(float32_t *)&v28;
                    *(float32_t *)&v28 = *(float32_t *)&v53 * *(float32_t *)&v52 + v120;
                    float32_t v121 = *(float32_t *)&v28;
                    *(float32_t *)&v28 = *(float32_t *)&v55 * *(float32_t *)&v54 + v121;
                    float32_t v122 = *(float32_t *)&v28;
                    *(float32_t *)&v28 = *(float32_t *)&v81 * *(float32_t *)&v79 + v122;
                    float32_t v123 = *(float32_t *)&v28;
                    *(float32_t *)&v28 = *(float32_t *)&v85 * *(float32_t *)&v83 + v123;
                    float32_t v124 = *(float32_t *)&v28;
                    *(float32_t *)&v28 = *(float32_t *)&v89 * *(float32_t *)&v87 + v124;
                    float32_t v125 = *(float32_t *)&v28;
                    *(float32_t *)&v28 = *(float32_t *)&v93 * *(float32_t *)&v91 + v125;
                    float32_t v126 = *(float32_t *)&v28;
                    *(float32_t *)&v28 = *(float32_t *)&v97 * *(float32_t *)&v95 + v126;
                    float32_t v127 = *(float32_t *)&v28;
                    *(float32_t *)&v28 = *(float32_t *)&v101 * *(float32_t *)&v99 + v127;
                    float32_t v128 = *(float32_t *)&v28;
                    *(float32_t *)&v28 = *(float32_t *)&v105 * *(float32_t *)&v103 + v128;
                    float32_t v129 = *(float32_t *)&v28;
                    *(float32_t *)&v23 = *(float32_t *)&v107 * *(float32_t *)&v109 + v129;
                    while (v110 > 12 && true) {
                        v59 = *(float32_t *)(char *)(0x100000000 * (int64_t)v18 | (int64_t)v112);
                        *(float32_t *)&v29 = v59;
                        v60 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v112) + 4);
                        *(float32_t *)&v30 = v60;
                        v61 = (int64_t)v26 * (int64_t)4 + (int64_t)v111;
                        v62 = (int32_t)((v61 & -0x100000000) >> 32);
                        v63 = (int32_t)v61;
                        v64 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v112) + 8);
                        *(float32_t *)&v32 = v64;
                        v65 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v112) + 12);
                        *(float32_t *)&v34 = v65;
                        v66 = *(float32_t *)(char *)(0x100000000 * (int64_t)v62 | (int64_t)v63);
                        *(float32_t *)&v28 = v66;
                        v67 = *(float32_t *)(char *)((0x100000000 * (int64_t)v62 | (int64_t)v63) + 4);
                        *(float32_t *)&v31 = v67;
                        v68 = *(float32_t *)(char *)((0x100000000 * (int64_t)v62 | (int64_t)v63) + 8);
                        *(float32_t *)&v33 = v68;
                        v69 = *(float32_t *)(char *)((0x100000000 * (int64_t)v62 | (int64_t)v63) + 12);
                        *(float32_t *)&v35 = v69;
                        v70 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v112) + 16);
                        *(float32_t *)&v48 = v70;
                        v71 = *(float32_t *)(char *)((0x100000000 * (int64_t)v62 | (int64_t)v63) + 16);
                        *(float32_t *)&v49 = v71;
                        v72 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v112) + 20);
                        *(float32_t *)&v50 = v72;
                        v73 = *(float32_t *)(char *)((0x100000000 * (int64_t)v62 | (int64_t)v63) + 20);
                        *(float32_t *)&v51 = v73;
                        v74 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v112) + 24);
                        *(float32_t *)&v52 = v74;
                        v75 = *(float32_t *)(char *)((0x100000000 * (int64_t)v62 | (int64_t)v63) + 24);
                        *(float32_t *)&v53 = v75;
                        v76 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v112) + 28);
                        *(float32_t *)&v54 = v76;
                        v77 = *(float32_t *)(char *)((0x100000000 * (int64_t)v62 | (int64_t)v63) + 28);
                        *(float32_t *)&v55 = v77;
                        v78 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v112) + 32);
                        *(float32_t *)&v79 = v78;
                        v80 = *(float32_t *)(char *)((0x100000000 * (int64_t)v62 | (int64_t)v63) + 32);
                        *(float32_t *)&v81 = v80;
                        v82 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v112) + 36);
                        *(float32_t *)&v83 = v82;
                        v84 = *(float32_t *)(char *)((0x100000000 * (int64_t)v62 | (int64_t)v63) + 36);
                        *(float32_t *)&v85 = v84;
                        v86 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v112) + 40);
                        *(float32_t *)&v87 = v86;
                        v88 = *(float32_t *)(char *)((0x100000000 * (int64_t)v62 | (int64_t)v63) + 40);
                        *(float32_t *)&v89 = v88;
                        v90 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v112) + 44);
                        *(float32_t *)&v91 = v90;
                        v92 = *(float32_t *)(char *)((0x100000000 * (int64_t)v62 | (int64_t)v63) + 44);
                        *(float32_t *)&v93 = v92;
                        v94 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v112) + 48);
                        *(float32_t *)&v95 = v94;
                        v96 = *(float32_t *)(char *)((0x100000000 * (int64_t)v62 | (int64_t)v63) + 48);
                        *(float32_t *)&v97 = v96;
                        v98 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v112) + 52);
                        *(float32_t *)&v99 = v98;
                        v100 = *(float32_t *)(char *)((0x100000000 * (int64_t)v62 | (int64_t)v63) + 52);
                        *(float32_t *)&v101 = v100;
                        v102 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v112) + 56);
                        *(float32_t *)&v103 = v102;
                        v104 = *(float32_t *)(char *)((0x100000000 * (int64_t)v62 | (int64_t)v63) + 56);
                        *(float32_t *)&v105 = v104;
                        v106 = *(float32_t *)(char *)((0x100000000 * (int64_t)v62 | (int64_t)v63) + 60);
                        *(float32_t *)&v107 = v106;
                        v108 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v112) + 60);
                        *(float32_t *)&v109 = v108;
                        v110 -= 16;
                        v1 = llvm_uadd_with_overflow_i32(v111, 64);
                        v2 = llvm_uadd_with_overflow_i32(v1.e0, 0);
                        v111 = v2.e0;
                        v3 = llvm_uadd_with_overflow_i32(v112, 64);
                        v4 = llvm_uadd_with_overflow_i32(v3.e0, 0);
                        v112 = v4.e0;
                        v113 = v113 + (int32_t)(v1.e1 | v2.e1) + (int32_t)0;
                        v37 += 16;
                        v18 = v18 + (int32_t)(v3.e1 | v4.e1) + (int32_t)0;
                        v114 = *(float32_t *)&v23;
                        *(float32_t *)&v28 = *(float32_t *)&v28 * *(float32_t *)&v29 + v114;
                        v115 = *(float32_t *)&v28;
                        *(float32_t *)&v28 = *(float32_t *)&v31 * *(float32_t *)&v30 + v115;
                        v116 = *(float32_t *)&v28;
                        *(float32_t *)&v28 = *(float32_t *)&v33 * *(float32_t *)&v32 + v116;
                        v117 = *(float32_t *)&v28;
                        *(float32_t *)&v28 = *(float32_t *)&v35 * *(float32_t *)&v34 + v117;
                        v118 = *(float32_t *)&v28;
                        *(float32_t *)&v28 = *(float32_t *)&v49 * *(float32_t *)&v48 + v118;
                        v119 = *(float32_t *)&v28;
                        *(float32_t *)&v28 = *(float32_t *)&v51 * *(float32_t *)&v50 + v119;
                        v120 = *(float32_t *)&v28;
                        *(float32_t *)&v28 = *(float32_t *)&v53 * *(float32_t *)&v52 + v120;
                        v121 = *(float32_t *)&v28;
                        *(float32_t *)&v28 = *(float32_t *)&v55 * *(float32_t *)&v54 + v121;
                        v122 = *(float32_t *)&v28;
                        *(float32_t *)&v28 = *(float32_t *)&v81 * *(float32_t *)&v79 + v122;
                        v123 = *(float32_t *)&v28;
                        *(float32_t *)&v28 = *(float32_t *)&v85 * *(float32_t *)&v83 + v123;
                        v124 = *(float32_t *)&v28;
                        *(float32_t *)&v28 = *(float32_t *)&v89 * *(float32_t *)&v87 + v124;
                        v125 = *(float32_t *)&v28;
                        *(float32_t *)&v28 = *(float32_t *)&v93 * *(float32_t *)&v91 + v125;
                        v126 = *(float32_t *)&v28;
                        *(float32_t *)&v28 = *(float32_t *)&v97 * *(float32_t *)&v95 + v126;
                        v127 = *(float32_t *)&v28;
                        *(float32_t *)&v28 = *(float32_t *)&v101 * *(float32_t *)&v99 + v127;
                        v128 = *(float32_t *)&v28;
                        *(float32_t *)&v28 = *(float32_t *)&v105 * *(float32_t *)&v103 + v128;
                        v129 = *(float32_t *)&v28;
                        *(float32_t *)&v23 = *(float32_t *)&v107 * *(float32_t *)&v109 + v129;
                    }
                    v57 = v111;
                    v47 = v110;
                    v58 = v113;
                    v56 = v112;
                } else {
                    v57 = v43;
                    v47 = v40;
                    v58 = v42;
                    v56 = v46;
                }
                int32_t v130;
                int32_t v131;
                int32_t v132;
                int32_t v133;
                if (v47 > 4 && true) {
                    float32_t v134 = *(float32_t *)(char *)(0x100000000 * (int64_t)v18 | (int64_t)v56);
                    *(float32_t *)&v29 = v134;
                    int64_t v135 = (int64_t)v26 * (int64_t)4 + (int64_t)v57;
                    uint32_t v136 = (int32_t)((v135 & -0x100000000) >> 32);
                    uint32_t v137 = (int32_t)v135;
                    float32_t v138 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v56) + 4);
                    *(float32_t *)&v30 = v138;
                    float32_t v139 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v56) + 8);
                    *(float32_t *)&v32 = v139;
                    float32_t v140 = *(float32_t *)(char *)(0x100000000 * (int64_t)v136 | (int64_t)v137);
                    *(float32_t *)&v28 = v140;
                    float32_t v141 = *(float32_t *)(char *)((0x100000000 * (int64_t)v136 | (int64_t)v137) + 4);
                    *(float32_t *)&v31 = v141;
                    float32_t v142 = *(float32_t *)(char *)((0x100000000 * (int64_t)v136 | (int64_t)v137) + 8);
                    *(float32_t *)&v33 = v142;
                    float32_t v143 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v56) + 12);
                    *(float32_t *)&v34 = v143;
                    float32_t v144 = *(float32_t *)(char *)((0x100000000 * (int64_t)v136 | (int64_t)v137) + 12);
                    *(float32_t *)&v35 = v144;
                    float32_t v145 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v56) + 16);
                    *(float32_t *)&v48 = v145;
                    float32_t v146 = *(float32_t *)(char *)((0x100000000 * (int64_t)v136 | (int64_t)v137) + 16);
                    *(float32_t *)&v49 = v146;
                    float32_t v147 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v56) + 20);
                    *(float32_t *)&v50 = v147;
                    float32_t v148 = *(float32_t *)(char *)((0x100000000 * (int64_t)v136 | (int64_t)v137) + 20);
                    *(float32_t *)&v51 = v148;
                    float32_t v149 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v56) + 24);
                    *(float32_t *)&v52 = v149;
                    float32_t v150 = *(float32_t *)(char *)((0x100000000 * (int64_t)v136 | (int64_t)v137) + 24);
                    *(float32_t *)&v53 = v150;
                    float32_t v151 = *(float32_t *)(char *)((0x100000000 * (int64_t)v136 | (int64_t)v137) + 28);
                    *(float32_t *)&v55 = v151;
                    float32_t v152 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v56) + 28);
                    *(float32_t *)&v54 = v152;
                    v5 = llvm_uadd_with_overflow_i32(v57, 32);
                    v6 = llvm_uadd_with_overflow_i32(v5.e0, 0);
                    v37 += 8;
                    v7 = llvm_uadd_with_overflow_i32(v56, 32);
                    v8 = llvm_uadd_with_overflow_i32(v7.e0, 0);
                    v18 = v18 + (int32_t)(v7.e1 | v8.e1) + (int32_t)0;
                    float32_t v153 = *(float32_t *)&v23;
                    *(float32_t *)&v28 = *(float32_t *)&v28 * *(float32_t *)&v29 + v153;
                    float32_t v154 = *(float32_t *)&v28;
                    *(float32_t *)&v28 = *(float32_t *)&v31 * *(float32_t *)&v30 + v154;
                    float32_t v155 = *(float32_t *)&v28;
                    *(float32_t *)&v28 = *(float32_t *)&v33 * *(float32_t *)&v32 + v155;
                    float32_t v156 = *(float32_t *)&v28;
                    *(float32_t *)&v28 = *(float32_t *)&v35 * *(float32_t *)&v34 + v156;
                    float32_t v157 = *(float32_t *)&v28;
                    *(float32_t *)&v28 = *(float32_t *)&v49 * *(float32_t *)&v48 + v157;
                    float32_t v158 = *(float32_t *)&v28;
                    *(float32_t *)&v28 = *(float32_t *)&v51 * *(float32_t *)&v50 + v158;
                    float32_t v159 = *(float32_t *)&v28;
                    *(float32_t *)&v28 = *(float32_t *)&v53 * *(float32_t *)&v52 + v159;
                    float32_t v160 = *(float32_t *)&v28;
                    *(float32_t *)&v23 = *(float32_t *)&v55 * *(float32_t *)&v54 + v160;
                    v132 = v6.e0;
                    v130 = v47 - 8;
                    v133 = v58 + (int32_t)(v5.e1 | v6.e1) + (int32_t)0;
                    v131 = v8.e0;
                } else {
                    v132 = v57;
                    v130 = v47;
                    v133 = v58;
                    v131 = v56;
                }
                if (v130 == 0 && !v44) {
                    goto lab__L_x_1;
                } else {
                    v38 = v132;
                    v27 = v130;
                    v39 = v133;
                    v36 = v131;
                    goto lab__L_x_2_preheader;
                }
            }
        }
    }
  lab__L_x_0:;
    float32_t v161 = *(float32_t *)&v23 >= 0.0f & true ? *(float32_t *)&v23 : 0.0f;
    *(float32_t *)&v19 = v161;
    int64_t v162 = (int64_t)(v19 * a7 + v21) * (int64_t)4 + (int64_t)a4;
    v18 = (v162 & -0x100000000) >> 32;
    float32_t v163 = *(float32_t *)&v19;
    *(float32_t *)(char *)(0x100000000 * (int64_t)v18 | (int64_t)(int32_t)v162) = v163;
  lab__L_x_1:
    if (v25 != 0 && true) {
        int64_t v164 = (int64_t)(v21 * a6 + v37) * (int64_t)4 + (int64_t)a2;
        v18 = (v164 & -0x100000000) >> 32;
        int64_t v165 = (int64_t)(v19 * a6 + v37) * (int64_t)4 + (int64_t)a1;
        int32_t v166 = v165;
        int32_t v167 = v18;
        int32_t v168 = (v165 & -0x100000000) >> 32;
        int32_t v169 = v25;
        int32_t v170 = v164;
        v18 = v167;
        float32_t v171 = *(float32_t *)(char *)(0x100000000 * (int64_t)v168 | (int64_t)v166);
        *(float32_t *)&v37 = v171;
        float32_t v172 = *(float32_t *)(char *)(0x100000000 * (int64_t)v18 | (int64_t)v170);
        *(float32_t *)&v18 = v172;
        v169--;
        v13 = llvm_uadd_with_overflow_i32(v166, 4);
        v14 = llvm_uadd_with_overflow_i32(v13.e0, 0);
        v15 = llvm_uadd_with_overflow_i32(v170, 4);
        v16 = llvm_uadd_with_overflow_i32(v15.e0, 0);
        *(float32_t *)&v23 = *(float32_t *)&v18 * *(float32_t *)&v37 + *(float32_t *)&v23;
        while (v169 != 0 && true) {
            v166 = v14.e0;
            v167 = v167 + (int32_t)(v15.e1 | v16.e1) + (int32_t)0;
            v168 = v168 + (int32_t)(v13.e1 | v14.e1) + (int32_t)0;
            v170 = v16.e0;
            v18 = v167;
            v171 = *(float32_t *)(char *)(0x100000000 * (int64_t)v168 | (int64_t)v166);
            *(float32_t *)&v37 = v171;
            v172 = *(float32_t *)(char *)(0x100000000 * (int64_t)v18 | (int64_t)v170);
            *(float32_t *)&v18 = v172;
            v169--;
            v13 = llvm_uadd_with_overflow_i32(v166, 4);
            v14 = llvm_uadd_with_overflow_i32(v13.e0, 0);
            v15 = llvm_uadd_with_overflow_i32(v170, 4);
            v16 = llvm_uadd_with_overflow_i32(v15.e0, 0);
            *(float32_t *)&v23 = *(float32_t *)&v18 * *(float32_t *)&v37 + *(float32_t *)&v23;
        }
    }
    goto lab__L_x_0;
  lab__L_x_2_preheader:;
    int32_t v173 = v39;
    float32_t v174 = *(float32_t *)(char *)(0x100000000 * (int64_t)v18 | (int64_t)v36);
    *(float32_t *)&v29 = v174;
    int64_t v175 = (int64_t)v26 * (int64_t)4 + (int64_t)v38;
    uint32_t v176 = (int32_t)((v175 & -0x100000000) >> 32);
    uint32_t v177 = (int32_t)v175;
    float32_t v178 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v36) + 4);
    *(float32_t *)&v30 = v178;
    float32_t v179 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v36) + 8);
    *(float32_t *)&v32 = v179;
    float32_t v180 = *(float32_t *)(char *)(0x100000000 * (int64_t)v176 | (int64_t)v177);
    *(float32_t *)&v28 = v180;
    float32_t v181 = *(float32_t *)(char *)((0x100000000 * (int64_t)v176 | (int64_t)v177) + 4);
    *(float32_t *)&v31 = v181;
    float32_t v182 = *(float32_t *)(char *)((0x100000000 * (int64_t)v176 | (int64_t)v177) + 8);
    *(float32_t *)&v33 = v182;
    float32_t v183 = *(float32_t *)(char *)((0x100000000 * (int64_t)v176 | (int64_t)v177) + 12);
    *(float32_t *)&v35 = v183;
    float32_t v184 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v36) + 12);
    *(float32_t *)&v34 = v184;
    int32_t v185 = v27 - 4;
    v9 = llvm_uadd_with_overflow_i32(v38, 16);
    v10 = llvm_uadd_with_overflow_i32(v9.e0, 0);
    v37 += 4;
    float32_t v186 = *(float32_t *)&v23;
    *(float32_t *)&v28 = *(float32_t *)&v28 * *(float32_t *)&v29 + v186;
    float32_t v187 = *(float32_t *)&v28;
    *(float32_t *)&v28 = *(float32_t *)&v31 * *(float32_t *)&v30 + v187;
    float32_t v188 = *(float32_t *)&v28;
    *(float32_t *)&v32 = *(float32_t *)&v33 * *(float32_t *)&v32 + v188;
    v11 = llvm_uadd_with_overflow_i32(v36, 16);
    v12 = llvm_uadd_with_overflow_i32(v11.e0, 0);
    v28 = v12.e0;
    v29 = v18 + (int32_t)(v11.e1 | v12.e1) + (int32_t)0;
    float32_t v189 = *(float32_t *)&v32;
    *(float32_t *)&v23 = *(float32_t *)&v35 * *(float32_t *)&v34 + v189;
    v18 = v29;
    while (v185 != 0 && true) {
        int32_t v190 = v10.e0;
        v173 = v173 + (int32_t)(v9.e1 | v10.e1) + (int32_t)0;
        v174 = *(float32_t *)(char *)(0x100000000 * (int64_t)v18 | (int64_t)v28);
        *(float32_t *)&v29 = v174;
        v175 = (int64_t)v26 * (int64_t)4 + (int64_t)v190;
        v176 = (int32_t)((v175 & -0x100000000) >> 32);
        v177 = (int32_t)v175;
        v178 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v28) + 4);
        *(float32_t *)&v30 = v178;
        v179 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v28) + 8);
        *(float32_t *)&v32 = v179;
        v180 = *(float32_t *)(char *)(0x100000000 * (int64_t)v176 | (int64_t)v177);
        *(float32_t *)&v28 = v180;
        v181 = *(float32_t *)(char *)((0x100000000 * (int64_t)v176 | (int64_t)v177) + 4);
        *(float32_t *)&v31 = v181;
        v182 = *(float32_t *)(char *)((0x100000000 * (int64_t)v176 | (int64_t)v177) + 8);
        *(float32_t *)&v33 = v182;
        v183 = *(float32_t *)(char *)((0x100000000 * (int64_t)v176 | (int64_t)v177) + 12);
        *(float32_t *)&v35 = v183;
        v184 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v28) + 12);
        *(float32_t *)&v34 = v184;
        v185 -= 4;
        v9 = llvm_uadd_with_overflow_i32(v190, 16);
        v10 = llvm_uadd_with_overflow_i32(v9.e0, 0);
        v37 += 4;
        v186 = *(float32_t *)&v23;
        *(float32_t *)&v28 = *(float32_t *)&v28 * *(float32_t *)&v29 + v186;
        v187 = *(float32_t *)&v28;
        *(float32_t *)&v28 = *(float32_t *)&v31 * *(float32_t *)&v30 + v187;
        v188 = *(float32_t *)&v28;
        *(float32_t *)&v32 = *(float32_t *)&v33 * *(float32_t *)&v32 + v188;
        v11 = llvm_uadd_with_overflow_i32(v28, 16);
        v12 = llvm_uadd_with_overflow_i32(v11.e0, 0);
        v28 = v12.e0;
        v29 = v18 + (int32_t)(v11.e1 | v12.e1) + (int32_t)0;
        v189 = *(float32_t *)&v32;
        *(float32_t *)&v23 = *(float32_t *)&v35 * *(float32_t *)&v34 + v189;
        v18 = v29;
    }
    goto lab__L_x_1;
}

void _Z18linear_proj_kernelPKfS0_S0_Pfiii(float32_t * a1, float32_t * a2, float32_t * a3, float32_t * a4, int32_t a5, int32_t a6, int32_t a7) {
    struct struct1 v1;
    struct struct1 v2;
    struct struct1 v3;
    struct struct1 v4;
    struct struct1 v5;
    struct struct1 v6;
    struct struct1 v7;
    struct struct1 v8;
    struct struct1 v9;
    struct struct1 v10;
    struct struct1 v11;
    struct struct1 v12;
    struct struct1 v13;
    struct struct1 v14;
    struct struct1 v15;
    struct struct1 v16;
    int32_t v17 = llvm_nvvm_read_ptx_sreg_ctaid_x();
    int32_t v18 = llvm_nvvm_read_ptx_sreg_tid_x();
    int32_t v19 = llvm_nvvm_read_ptx_sreg_ctaid_y();
    int32_t v20 = llvm_nvvm_read_ptx_sreg_tid_y();
    int32_t v21 = v17 * llvm_nvvm_read_ptx_sreg_ntid_x() + v18;
    int32_t v22 = v19 * llvm_nvvm_read_ptx_sreg_ntid_y() + v20;
    if (v22 >= a5 || v21 >= a7 && true) {
        return;
    }
    int64_t v23 = (int64_t)v21 * (int64_t)4 + (int64_t)a3;
    v18 = (v23 & -0x100000000) >> 32;
    float32_t v24 = *(float32_t *)(char *)(0x100000000 * (int64_t)v18 | (int64_t)(int32_t)v23);
    int32_t v25;
    *(float32_t *)&v25 = v24;
    int32_t v26;
    uint32_t v27;
    int32_t v28;
    int32_t v29;
    int32_t v30;
    int32_t v31;
    int32_t v32;
    int32_t v33;
    int32_t v34;
    int32_t v35;
    int32_t v36;
    int32_t v37;
    int32_t v38;
    int32_t v39;
    int32_t v40;
    int32_t v41;
    int32_t v42;
    if (a6 < 1 || false) {
        goto lab__L_x_8;
    } else {
        v26 = a6 & 3;
        if (a6 < 4 || false) {
            v29 = 0;
            goto lab__L_x_9;
        } else {
            int32_t v43 = a6 - v26;
            int64_t v44 = (int64_t)a2;
            int32_t v45 = (v44 & -0x100000000) >> 32;
            int32_t v46 = v44;
            v27 = v21 * a6;
            bool v47 = v43 > 0 & true;
            int32_t v48 = 0;
            int64_t v49 = (int64_t)(v22 * a6) * (int64_t)4 + (int64_t)a1;
            int32_t v50 = v49;
            v18 = (v49 & -0x100000000) >> 32;
            if (!v47) {
                v41 = v46;
                v30 = v43;
                v28 = v48;
                v42 = v45;
                v39 = v50;
                goto lab__L_x_10_preheader;
            } else {
                int32_t v51;
                int32_t v52;
                int32_t v53;
                int32_t v54;
                int32_t v55;
                int32_t v56;
                int32_t v57;
                int32_t v58;
                int32_t v59;
                int32_t v60;
                uint32_t v61;
                int32_t v62;
                int32_t v63;
                if (v43 > 12 && true) {
                    v40 = v46;
                    float32_t v64 = *(float32_t *)(char *)(0x100000000 * (int64_t)v18 | (int64_t)v50);
                    *(float32_t *)&v32 = v64;
                    float32_t v65 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v50) + 4);
                    *(float32_t *)&v33 = v65;
                    int64_t v66 = (int64_t)v27 * (int64_t)4 + (int64_t)v40;
                    uint32_t v67 = (int32_t)((v66 & -0x100000000) >> 32);
                    v40 = v66;
                    float32_t v68 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v50) + 8);
                    *(float32_t *)&v35 = v68;
                    float32_t v69 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v50) + 12);
                    *(float32_t *)&v37 = v69;
                    float32_t v70 = *(float32_t *)(char *)(0x100000000 * (int64_t)v67 | (int64_t)v40);
                    *(float32_t *)&v31 = v70;
                    float32_t v71 = *(float32_t *)(char *)((0x100000000 * (int64_t)v67 | (int64_t)v40) + 4);
                    *(float32_t *)&v34 = v71;
                    float32_t v72 = *(float32_t *)(char *)((0x100000000 * (int64_t)v67 | (int64_t)v40) + 8);
                    *(float32_t *)&v36 = v72;
                    float32_t v73 = *(float32_t *)(char *)((0x100000000 * (int64_t)v67 | (int64_t)v40) + 12);
                    *(float32_t *)&v38 = v73;
                    float32_t v74 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v50) + 16);
                    *(float32_t *)&v53 = v74;
                    float32_t v75 = *(float32_t *)(char *)((0x100000000 * (int64_t)v67 | (int64_t)v40) + 16);
                    *(float32_t *)&v54 = v75;
                    float32_t v76 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v50) + 20);
                    *(float32_t *)&v55 = v76;
                    float32_t v77 = *(float32_t *)(char *)((0x100000000 * (int64_t)v67 | (int64_t)v40) + 20);
                    *(float32_t *)&v56 = v77;
                    float32_t v78 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v50) + 24);
                    *(float32_t *)&v57 = v78;
                    float32_t v79 = *(float32_t *)(char *)((0x100000000 * (int64_t)v67 | (int64_t)v40) + 24);
                    *(float32_t *)&v58 = v79;
                    float32_t v80 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v50) + 28);
                    *(float32_t *)&v59 = v80;
                    float32_t v81 = *(float32_t *)(char *)((0x100000000 * (int64_t)v67 | (int64_t)v40) + 28);
                    *(float32_t *)&v60 = v81;
                    float32_t v82 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v50) + 32);
                    int32_t v83;
                    *(float32_t *)&v83 = v82;
                    float32_t v84 = *(float32_t *)(char *)((0x100000000 * (int64_t)v67 | (int64_t)v40) + 32);
                    int32_t v85;
                    *(float32_t *)&v85 = v84;
                    float32_t v86 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v50) + 36);
                    int32_t v87;
                    *(float32_t *)&v87 = v86;
                    float32_t v88 = *(float32_t *)(char *)((0x100000000 * (int64_t)v67 | (int64_t)v40) + 36);
                    int32_t v89;
                    *(float32_t *)&v89 = v88;
                    float32_t v90 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v50) + 40);
                    int32_t v91;
                    *(float32_t *)&v91 = v90;
                    float32_t v92 = *(float32_t *)(char *)((0x100000000 * (int64_t)v67 | (int64_t)v40) + 40);
                    int32_t v93;
                    *(float32_t *)&v93 = v92;
                    float32_t v94 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v50) + 44);
                    int32_t v95;
                    *(float32_t *)&v95 = v94;
                    float32_t v96 = *(float32_t *)(char *)((0x100000000 * (int64_t)v67 | (int64_t)v40) + 44);
                    int32_t v97;
                    *(float32_t *)&v97 = v96;
                    float32_t v98 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v50) + 48);
                    int32_t v99;
                    *(float32_t *)&v99 = v98;
                    float32_t v100 = *(float32_t *)(char *)((0x100000000 * (int64_t)v67 | (int64_t)v40) + 48);
                    int32_t v101;
                    *(float32_t *)&v101 = v100;
                    float32_t v102 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v50) + 52);
                    int32_t v103;
                    *(float32_t *)&v103 = v102;
                    float32_t v104 = *(float32_t *)(char *)((0x100000000 * (int64_t)v67 | (int64_t)v40) + 52);
                    int32_t v105;
                    *(float32_t *)&v105 = v104;
                    float32_t v106 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v50) + 56);
                    int32_t v107;
                    *(float32_t *)&v107 = v106;
                    float32_t v108 = *(float32_t *)(char *)((0x100000000 * (int64_t)v67 | (int64_t)v40) + 56);
                    int32_t v109;
                    *(float32_t *)&v109 = v108;
                    float32_t v110 = *(float32_t *)(char *)((0x100000000 * (int64_t)v67 | (int64_t)v40) + 60);
                    int32_t v111;
                    *(float32_t *)&v111 = v110;
                    float32_t v112 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v50) + 60);
                    int32_t v113;
                    *(float32_t *)&v113 = v112;
                    int32_t v114 = v43 - 16;
                    v1 = llvm_uadd_with_overflow_i32(v46, 64);
                    v2 = llvm_uadd_with_overflow_i32(v1.e0, 0);
                    int32_t v115 = v2.e0;
                    v3 = llvm_uadd_with_overflow_i32(v50, 64);
                    v4 = llvm_uadd_with_overflow_i32(v3.e0, 0);
                    int32_t v116 = v4.e0;
                    int32_t v117 = v45 + (int32_t)(v1.e1 | v2.e1) + (int32_t)0;
                    int32_t v118 = 16 + v48;
                    v18 = v18 + (int32_t)(v3.e1 | v4.e1) + (int32_t)0;
                    *(float32_t *)&v31 = *(float32_t *)&v31 * *(float32_t *)&v32 + *(float32_t *)&v25;
                    float32_t v119 = *(float32_t *)&v31;
                    *(float32_t *)&v31 = *(float32_t *)&v34 * *(float32_t *)&v33 + v119;
                    float32_t v120 = *(float32_t *)&v31;
                    *(float32_t *)&v31 = *(float32_t *)&v36 * *(float32_t *)&v35 + v120;
                    float32_t v121 = *(float32_t *)&v31;
                    *(float32_t *)&v31 = *(float32_t *)&v38 * *(float32_t *)&v37 + v121;
                    float32_t v122 = *(float32_t *)&v31;
                    *(float32_t *)&v31 = *(float32_t *)&v54 * *(float32_t *)&v53 + v122;
                    float32_t v123 = *(float32_t *)&v31;
                    *(float32_t *)&v31 = *(float32_t *)&v56 * *(float32_t *)&v55 + v123;
                    float32_t v124 = *(float32_t *)&v31;
                    *(float32_t *)&v31 = *(float32_t *)&v58 * *(float32_t *)&v57 + v124;
                    float32_t v125 = *(float32_t *)&v31;
                    *(float32_t *)&v31 = *(float32_t *)&v60 * *(float32_t *)&v59 + v125;
                    float32_t v126 = *(float32_t *)&v31;
                    *(float32_t *)&v31 = *(float32_t *)&v85 * *(float32_t *)&v83 + v126;
                    float32_t v127 = *(float32_t *)&v31;
                    *(float32_t *)&v31 = *(float32_t *)&v89 * *(float32_t *)&v87 + v127;
                    float32_t v128 = *(float32_t *)&v31;
                    *(float32_t *)&v31 = *(float32_t *)&v93 * *(float32_t *)&v91 + v128;
                    float32_t v129 = *(float32_t *)&v31;
                    *(float32_t *)&v31 = *(float32_t *)&v97 * *(float32_t *)&v95 + v129;
                    float32_t v130 = *(float32_t *)&v31;
                    *(float32_t *)&v31 = *(float32_t *)&v101 * *(float32_t *)&v99 + v130;
                    float32_t v131 = *(float32_t *)&v31;
                    *(float32_t *)&v31 = *(float32_t *)&v105 * *(float32_t *)&v103 + v131;
                    float32_t v132 = *(float32_t *)&v31;
                    *(float32_t *)&v31 = *(float32_t *)&v109 * *(float32_t *)&v107 + v132;
                    *(float32_t *)&v25 = *(float32_t *)&v111 * *(float32_t *)&v113 + *(float32_t *)&v31;
                    while (v114 > 12 && true) {
                        v40 = v115;
                        v64 = *(float32_t *)(char *)(0x100000000 * (int64_t)v18 | (int64_t)v116);
                        *(float32_t *)&v32 = v64;
                        v65 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v116) + 4);
                        *(float32_t *)&v33 = v65;
                        v66 = (int64_t)v27 * (int64_t)4 + (int64_t)v40;
                        v67 = (int32_t)((v66 & -0x100000000) >> 32);
                        v40 = v66;
                        v68 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v116) + 8);
                        *(float32_t *)&v35 = v68;
                        v69 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v116) + 12);
                        *(float32_t *)&v37 = v69;
                        v70 = *(float32_t *)(char *)(0x100000000 * (int64_t)v67 | (int64_t)v40);
                        *(float32_t *)&v31 = v70;
                        v71 = *(float32_t *)(char *)((0x100000000 * (int64_t)v67 | (int64_t)v40) + 4);
                        *(float32_t *)&v34 = v71;
                        v72 = *(float32_t *)(char *)((0x100000000 * (int64_t)v67 | (int64_t)v40) + 8);
                        *(float32_t *)&v36 = v72;
                        v73 = *(float32_t *)(char *)((0x100000000 * (int64_t)v67 | (int64_t)v40) + 12);
                        *(float32_t *)&v38 = v73;
                        v74 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v116) + 16);
                        *(float32_t *)&v53 = v74;
                        v75 = *(float32_t *)(char *)((0x100000000 * (int64_t)v67 | (int64_t)v40) + 16);
                        *(float32_t *)&v54 = v75;
                        v76 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v116) + 20);
                        *(float32_t *)&v55 = v76;
                        v77 = *(float32_t *)(char *)((0x100000000 * (int64_t)v67 | (int64_t)v40) + 20);
                        *(float32_t *)&v56 = v77;
                        v78 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v116) + 24);
                        *(float32_t *)&v57 = v78;
                        v79 = *(float32_t *)(char *)((0x100000000 * (int64_t)v67 | (int64_t)v40) + 24);
                        *(float32_t *)&v58 = v79;
                        v80 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v116) + 28);
                        *(float32_t *)&v59 = v80;
                        v81 = *(float32_t *)(char *)((0x100000000 * (int64_t)v67 | (int64_t)v40) + 28);
                        *(float32_t *)&v60 = v81;
                        v82 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v116) + 32);
                        *(float32_t *)&v83 = v82;
                        v84 = *(float32_t *)(char *)((0x100000000 * (int64_t)v67 | (int64_t)v40) + 32);
                        *(float32_t *)&v85 = v84;
                        v86 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v116) + 36);
                        *(float32_t *)&v87 = v86;
                        v88 = *(float32_t *)(char *)((0x100000000 * (int64_t)v67 | (int64_t)v40) + 36);
                        *(float32_t *)&v89 = v88;
                        v90 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v116) + 40);
                        *(float32_t *)&v91 = v90;
                        v92 = *(float32_t *)(char *)((0x100000000 * (int64_t)v67 | (int64_t)v40) + 40);
                        *(float32_t *)&v93 = v92;
                        v94 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v116) + 44);
                        *(float32_t *)&v95 = v94;
                        v96 = *(float32_t *)(char *)((0x100000000 * (int64_t)v67 | (int64_t)v40) + 44);
                        *(float32_t *)&v97 = v96;
                        v98 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v116) + 48);
                        *(float32_t *)&v99 = v98;
                        v100 = *(float32_t *)(char *)((0x100000000 * (int64_t)v67 | (int64_t)v40) + 48);
                        *(float32_t *)&v101 = v100;
                        v102 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v116) + 52);
                        *(float32_t *)&v103 = v102;
                        v104 = *(float32_t *)(char *)((0x100000000 * (int64_t)v67 | (int64_t)v40) + 52);
                        *(float32_t *)&v105 = v104;
                        v106 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v116) + 56);
                        *(float32_t *)&v107 = v106;
                        v108 = *(float32_t *)(char *)((0x100000000 * (int64_t)v67 | (int64_t)v40) + 56);
                        *(float32_t *)&v109 = v108;
                        v110 = *(float32_t *)(char *)((0x100000000 * (int64_t)v67 | (int64_t)v40) + 60);
                        *(float32_t *)&v111 = v110;
                        v112 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v116) + 60);
                        *(float32_t *)&v113 = v112;
                        v114 -= 16;
                        v1 = llvm_uadd_with_overflow_i32(v115, 64);
                        v2 = llvm_uadd_with_overflow_i32(v1.e0, 0);
                        v115 = v2.e0;
                        v3 = llvm_uadd_with_overflow_i32(v116, 64);
                        v4 = llvm_uadd_with_overflow_i32(v3.e0, 0);
                        v116 = v4.e0;
                        v117 = v117 + (int32_t)(v1.e1 | v2.e1) + (int32_t)0;
                        v118 += 16;
                        v18 = v18 + (int32_t)(v3.e1 | v4.e1) + (int32_t)0;
                        *(float32_t *)&v31 = *(float32_t *)&v31 * *(float32_t *)&v32 + *(float32_t *)&v25;
                        v119 = *(float32_t *)&v31;
                        *(float32_t *)&v31 = *(float32_t *)&v34 * *(float32_t *)&v33 + v119;
                        v120 = *(float32_t *)&v31;
                        *(float32_t *)&v31 = *(float32_t *)&v36 * *(float32_t *)&v35 + v120;
                        v121 = *(float32_t *)&v31;
                        *(float32_t *)&v31 = *(float32_t *)&v38 * *(float32_t *)&v37 + v121;
                        v122 = *(float32_t *)&v31;
                        *(float32_t *)&v31 = *(float32_t *)&v54 * *(float32_t *)&v53 + v122;
                        v123 = *(float32_t *)&v31;
                        *(float32_t *)&v31 = *(float32_t *)&v56 * *(float32_t *)&v55 + v123;
                        v124 = *(float32_t *)&v31;
                        *(float32_t *)&v31 = *(float32_t *)&v58 * *(float32_t *)&v57 + v124;
                        v125 = *(float32_t *)&v31;
                        *(float32_t *)&v31 = *(float32_t *)&v60 * *(float32_t *)&v59 + v125;
                        v126 = *(float32_t *)&v31;
                        *(float32_t *)&v31 = *(float32_t *)&v85 * *(float32_t *)&v83 + v126;
                        v127 = *(float32_t *)&v31;
                        *(float32_t *)&v31 = *(float32_t *)&v89 * *(float32_t *)&v87 + v127;
                        v128 = *(float32_t *)&v31;
                        *(float32_t *)&v31 = *(float32_t *)&v93 * *(float32_t *)&v91 + v128;
                        v129 = *(float32_t *)&v31;
                        *(float32_t *)&v31 = *(float32_t *)&v97 * *(float32_t *)&v95 + v129;
                        v130 = *(float32_t *)&v31;
                        *(float32_t *)&v31 = *(float32_t *)&v101 * *(float32_t *)&v99 + v130;
                        v131 = *(float32_t *)&v31;
                        *(float32_t *)&v31 = *(float32_t *)&v105 * *(float32_t *)&v103 + v131;
                        v132 = *(float32_t *)&v31;
                        *(float32_t *)&v31 = *(float32_t *)&v109 * *(float32_t *)&v107 + v132;
                        *(float32_t *)&v25 = *(float32_t *)&v111 * *(float32_t *)&v113 + *(float32_t *)&v31;
                    }
                    v62 = v115;
                    v52 = v114;
                    v51 = v118;
                    v63 = v117;
                    v61 = v116;
                } else {
                    v62 = v46;
                    v52 = v43;
                    v51 = v48;
                    v63 = v45;
                    v61 = v50;
                }
                int32_t v133;
                int32_t v134;
                int32_t v135;
                int32_t v136;
                int32_t v137;
                if (v52 > 4 && true) {
                    v40 = v62;
                    float32_t v138 = *(float32_t *)(char *)(0x100000000 * (int64_t)v18 | (int64_t)v61);
                    *(float32_t *)&v32 = v138;
                    int64_t v139 = (int64_t)v27 * (int64_t)4 + (int64_t)v40;
                    uint32_t v140 = (int32_t)((v139 & -0x100000000) >> 32);
                    v40 = v139;
                    float32_t v141 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v61) + 4);
                    *(float32_t *)&v33 = v141;
                    float32_t v142 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v61) + 8);
                    *(float32_t *)&v35 = v142;
                    float32_t v143 = *(float32_t *)(char *)(0x100000000 * (int64_t)v140 | (int64_t)v40);
                    *(float32_t *)&v31 = v143;
                    float32_t v144 = *(float32_t *)(char *)((0x100000000 * (int64_t)v140 | (int64_t)v40) + 4);
                    *(float32_t *)&v34 = v144;
                    float32_t v145 = *(float32_t *)(char *)((0x100000000 * (int64_t)v140 | (int64_t)v40) + 8);
                    *(float32_t *)&v36 = v145;
                    float32_t v146 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v61) + 12);
                    *(float32_t *)&v37 = v146;
                    float32_t v147 = *(float32_t *)(char *)((0x100000000 * (int64_t)v140 | (int64_t)v40) + 12);
                    *(float32_t *)&v38 = v147;
                    float32_t v148 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v61) + 16);
                    *(float32_t *)&v53 = v148;
                    float32_t v149 = *(float32_t *)(char *)((0x100000000 * (int64_t)v140 | (int64_t)v40) + 16);
                    *(float32_t *)&v54 = v149;
                    float32_t v150 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v61) + 20);
                    *(float32_t *)&v55 = v150;
                    float32_t v151 = *(float32_t *)(char *)((0x100000000 * (int64_t)v140 | (int64_t)v40) + 20);
                    *(float32_t *)&v56 = v151;
                    float32_t v152 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v61) + 24);
                    *(float32_t *)&v57 = v152;
                    float32_t v153 = *(float32_t *)(char *)((0x100000000 * (int64_t)v140 | (int64_t)v40) + 24);
                    *(float32_t *)&v58 = v153;
                    float32_t v154 = *(float32_t *)(char *)((0x100000000 * (int64_t)v140 | (int64_t)v40) + 28);
                    *(float32_t *)&v60 = v154;
                    float32_t v155 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v61) + 28);
                    *(float32_t *)&v59 = v155;
                    v5 = llvm_uadd_with_overflow_i32(v62, 32);
                    v6 = llvm_uadd_with_overflow_i32(v5.e0, 0);
                    v7 = llvm_uadd_with_overflow_i32(v61, 32);
                    v8 = llvm_uadd_with_overflow_i32(v7.e0, 0);
                    v18 = v18 + (int32_t)(v7.e1 | v8.e1) + (int32_t)0;
                    *(float32_t *)&v31 = *(float32_t *)&v31 * *(float32_t *)&v32 + *(float32_t *)&v25;
                    float32_t v156 = *(float32_t *)&v31;
                    *(float32_t *)&v31 = *(float32_t *)&v34 * *(float32_t *)&v33 + v156;
                    float32_t v157 = *(float32_t *)&v31;
                    *(float32_t *)&v31 = *(float32_t *)&v36 * *(float32_t *)&v35 + v157;
                    float32_t v158 = *(float32_t *)&v31;
                    *(float32_t *)&v31 = *(float32_t *)&v38 * *(float32_t *)&v37 + v158;
                    float32_t v159 = *(float32_t *)&v31;
                    *(float32_t *)&v31 = *(float32_t *)&v54 * *(float32_t *)&v53 + v159;
                    float32_t v160 = *(float32_t *)&v31;
                    *(float32_t *)&v31 = *(float32_t *)&v56 * *(float32_t *)&v55 + v160;
                    float32_t v161 = *(float32_t *)&v31;
                    *(float32_t *)&v31 = *(float32_t *)&v58 * *(float32_t *)&v57 + v161;
                    *(float32_t *)&v25 = *(float32_t *)&v60 * *(float32_t *)&v59 + *(float32_t *)&v31;
                    v136 = v6.e0;
                    v134 = v52 - 8;
                    v133 = 8 + v51;
                    v137 = v63 + (int32_t)(v5.e1 | v6.e1) + (int32_t)0;
                    v135 = v8.e0;
                } else {
                    v136 = v62;
                    v134 = v52;
                    v133 = v51;
                    v137 = v63;
                    v135 = v61;
                }
                if (v134 == 0 && !v47) {
                    v29 = v133;
                    goto lab__L_x_9;
                } else {
                    v41 = v136;
                    v30 = v134;
                    v28 = v133;
                    v42 = v137;
                    v39 = v135;
                    goto lab__L_x_10_preheader;
                }
            }
        }
    }
  lab__L_x_8:;
    int64_t v162 = (int64_t)(v22 * a7 + v21) * (int64_t)4 + (int64_t)a4;
    v18 = (v162 & -0x100000000) >> 32;
    float32_t v163 = *(float32_t *)&v25;
    *(float32_t *)(char *)(0x100000000 * (int64_t)v18 | (int64_t)(int32_t)v162) = v163;
  lab__L_x_9:
    if (v26 != 0 && true) {
        v40 = v22 * a6 + v29;
        int64_t v164 = (int64_t)(v21 * a6 + v29) * (int64_t)4 + (int64_t)a2;
        v18 = (v164 & -0x100000000) >> 32;
        int64_t v165 = (int64_t)v40 * (int64_t)4 + (int64_t)a1;
        v40 = v165;
        int32_t v166 = v18;
        int32_t v167 = v40;
        int32_t v168 = (v165 & -0x100000000) >> 32;
        int32_t v169 = v26;
        int32_t v170 = v164;
        v18 = v166;
        v40 = v167;
        float32_t v171 = *(float32_t *)(char *)(0x100000000 * (int64_t)v18 | (int64_t)v170);
        *(float32_t *)&v18 = v171;
        float32_t v172 = *(float32_t *)(char *)(0x100000000 * (int64_t)v168 | (int64_t)v40);
        *(float32_t *)&v40 = v172;
        v169--;
        v13 = llvm_uadd_with_overflow_i32(v167, 4);
        v14 = llvm_uadd_with_overflow_i32(v13.e0, 0);
        v15 = llvm_uadd_with_overflow_i32(v170, 4);
        v16 = llvm_uadd_with_overflow_i32(v15.e0, 0);
        *(float32_t *)&v25 = *(float32_t *)&v18 * *(float32_t *)&v40 + *(float32_t *)&v25;
        while (v169 != 0 && true) {
            v166 = v166 + (int32_t)(v15.e1 | v16.e1) + (int32_t)0;
            v167 = v14.e0;
            v168 = v168 + (int32_t)(v13.e1 | v14.e1) + (int32_t)0;
            v170 = v16.e0;
            v18 = v166;
            v40 = v167;
            v171 = *(float32_t *)(char *)(0x100000000 * (int64_t)v18 | (int64_t)v170);
            *(float32_t *)&v18 = v171;
            v172 = *(float32_t *)(char *)(0x100000000 * (int64_t)v168 | (int64_t)v40);
            *(float32_t *)&v40 = v172;
            v169--;
            v13 = llvm_uadd_with_overflow_i32(v167, 4);
            v14 = llvm_uadd_with_overflow_i32(v13.e0, 0);
            v15 = llvm_uadd_with_overflow_i32(v170, 4);
            v16 = llvm_uadd_with_overflow_i32(v15.e0, 0);
            *(float32_t *)&v25 = *(float32_t *)&v18 * *(float32_t *)&v40 + *(float32_t *)&v25;
        }
    }
    goto lab__L_x_8;
  lab__L_x_10_preheader:;
    int32_t v173 = v42;
    v40 = v41;
    float32_t v174 = *(float32_t *)(char *)(0x100000000 * (int64_t)v18 | (int64_t)v39);
    *(float32_t *)&v32 = v174;
    int64_t v175 = (int64_t)v27 * (int64_t)4 + (int64_t)v40;
    uint32_t v176 = (int32_t)((v175 & -0x100000000) >> 32);
    v40 = v175;
    float32_t v177 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v39) + 4);
    *(float32_t *)&v33 = v177;
    float32_t v178 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v39) + 8);
    *(float32_t *)&v35 = v178;
    float32_t v179 = *(float32_t *)(char *)(0x100000000 * (int64_t)v176 | (int64_t)v40);
    *(float32_t *)&v31 = v179;
    float32_t v180 = *(float32_t *)(char *)((0x100000000 * (int64_t)v176 | (int64_t)v40) + 4);
    *(float32_t *)&v34 = v180;
    float32_t v181 = *(float32_t *)(char *)((0x100000000 * (int64_t)v176 | (int64_t)v40) + 8);
    *(float32_t *)&v36 = v181;
    float32_t v182 = *(float32_t *)(char *)((0x100000000 * (int64_t)v176 | (int64_t)v40) + 12);
    *(float32_t *)&v38 = v182;
    float32_t v183 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v39) + 12);
    *(float32_t *)&v37 = v183;
    int32_t v184 = v30 - 4;
    v9 = llvm_uadd_with_overflow_i32(v41, 16);
    v10 = llvm_uadd_with_overflow_i32(v9.e0, 0);
    int32_t v185 = 4 + v28;
    *(float32_t *)&v31 = *(float32_t *)&v31 * *(float32_t *)&v32 + *(float32_t *)&v25;
    float32_t v186 = *(float32_t *)&v31;
    *(float32_t *)&v31 = *(float32_t *)&v34 * *(float32_t *)&v33 + v186;
    float32_t v187 = *(float32_t *)&v31;
    *(float32_t *)&v35 = *(float32_t *)&v36 * *(float32_t *)&v35 + v187;
    v11 = llvm_uadd_with_overflow_i32(v39, 16);
    v12 = llvm_uadd_with_overflow_i32(v11.e0, 0);
    v31 = v12.e0;
    v32 = v18 + (int32_t)(v11.e1 | v12.e1) + (int32_t)0;
    *(float32_t *)&v25 = *(float32_t *)&v38 * *(float32_t *)&v37 + *(float32_t *)&v35;
    v18 = v32;
    while (v184 != 0 && true) {
        int32_t v188 = v10.e0;
        v173 = v173 + (int32_t)(v9.e1 | v10.e1) + (int32_t)0;
        v40 = v188;
        v174 = *(float32_t *)(char *)(0x100000000 * (int64_t)v18 | (int64_t)v31);
        *(float32_t *)&v32 = v174;
        v175 = (int64_t)v27 * (int64_t)4 + (int64_t)v40;
        v176 = (int32_t)((v175 & -0x100000000) >> 32);
        v40 = v175;
        v177 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v31) + 4);
        *(float32_t *)&v33 = v177;
        v178 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v31) + 8);
        *(float32_t *)&v35 = v178;
        v179 = *(float32_t *)(char *)(0x100000000 * (int64_t)v176 | (int64_t)v40);
        *(float32_t *)&v31 = v179;
        v180 = *(float32_t *)(char *)((0x100000000 * (int64_t)v176 | (int64_t)v40) + 4);
        *(float32_t *)&v34 = v180;
        v181 = *(float32_t *)(char *)((0x100000000 * (int64_t)v176 | (int64_t)v40) + 8);
        *(float32_t *)&v36 = v181;
        v182 = *(float32_t *)(char *)((0x100000000 * (int64_t)v176 | (int64_t)v40) + 12);
        *(float32_t *)&v38 = v182;
        v183 = *(float32_t *)(char *)((0x100000000 * (int64_t)v18 | (int64_t)v31) + 12);
        *(float32_t *)&v37 = v183;
        v184 -= 4;
        v9 = llvm_uadd_with_overflow_i32(v188, 16);
        v10 = llvm_uadd_with_overflow_i32(v9.e0, 0);
        v185 += 4;
        *(float32_t *)&v31 = *(float32_t *)&v31 * *(float32_t *)&v32 + *(float32_t *)&v25;
        v186 = *(float32_t *)&v31;
        *(float32_t *)&v31 = *(float32_t *)&v34 * *(float32_t *)&v33 + v186;
        v187 = *(float32_t *)&v31;
        *(float32_t *)&v35 = *(float32_t *)&v36 * *(float32_t *)&v35 + v187;
        v11 = llvm_uadd_with_overflow_i32(v31, 16);
        v12 = llvm_uadd_with_overflow_i32(v11.e0, 0);
        v31 = v12.e0;
        v32 = v18 + (int32_t)(v11.e1 | v12.e1) + (int32_t)0;
        *(float32_t *)&v25 = *(float32_t *)&v38 * *(float32_t *)&v37 + *(float32_t *)&v35;
        v18 = v32;
    }
    v29 = v185;
    goto lab__L_x_9;
}

// --------------------- Meta-Information ---------------------

// Detected functions: 5

